---

- name: Wordpress Playbook
  hosts: all
  become: yes


  tasks:

  - name: Install Apache2 and PHP package then Update repo index
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      force_apt_get: yes

  - name: Start Apache2
    service:
      name: apache2
      state: started

