---
- name: Wordpress Playbook
  hosts: all
  become: yes


  tasks:
  - name: Install Apache2 and PHP package then Update repo index
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - wget
        - php-mysql
        - php
        - php-curl
        - php-json
        - php-cgi
        - python3
        - python3-pexpect
        - python3-mysqldb
      state: latest
      force_apt_get: yes

  - name: Start Apache2
    service:
      name: apache2
      state: started

  - name: "Install MySQL Server Community"
    apt: 
      name: 
        - default-mysql-server
      state: latest

  - name: Start MySQL Service
    service: 
      name: mariadb
      state: started

  - name: Removes anonymous user account for localhost
    community.mysql.mysql_user:
      login_user: root
      login_password: 'password'
      name: ''
      host: localhost
      state: absent
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: Removes all anonymous user accounts
    community.mysql.mysql_user:
      name: ''
      host_all: true
      state: absent

  - name: "Create database user with name 'debian' and password 'password' with all database privileges"
    community.mysql.mysql_user:
      name: debian
      password: password
      priv: '*.*:ALL'
      state: present

  - name: Install ufw
    apt:
      name: ufw
      state: latest

  - name: Enable UFW
    community.general.ufw:
      state: enabled
      policy: allow

  - name: UFW Configuration
    ufw: 
      rule: allow
      port: '80'
      proto: tcp

  - name: Create a db called Wordpress
    community.mysql.mysql_db:
      name: wordpress
      state: present

  - name: Reload privilege tables
    command: mysql -e "FLUSH PRIVILEGES;"

  - name: Download and Unpack Latest Wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
      creates: /var/www/html/wordpress

#  - name: Install Wordpress
#   get_url:
#      url: "https://wordpress.org/latest.tar.gz"
#      dest: /var/www/html/

#  - name: Unpack Wordpress Archive
#    ansible.builtin.unarchive:
#      src: /var/www/html/wordpress-6.3.1.tar.gz
#      dest: /var/www/html/
#      remote_src: no

  - name: Wordpress Config file
    template:
      src: files/wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: Set up a virtual host
    template: 
      src: files/apache.conf.j2
      dest: /etc/apache2/sites-available/wordpress.conf

  - name: Enable new site
    command: a2ensite wordpress
 
  - name: Disable default apache site
    command: a2dissite 000-default.conf
  

  - name: Reload Apache
    service:
      name: apache2
      state: started

  - name: Remove index.html file
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Move files
    shell: mv /var/www/html/wordpress/* /var/www/html/
  
